### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by longnd** [htoo-eain-lwin/seeker#17]
Hello Htoo 👋 , thank you for your effort on the code submission. I am Long, engineering lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by htoo-eain-lwin** [comment]
Hello @longnd,

Nice to meet you. It's actually great process. First of all, I am really thankful for your time for creating issues. I do really want to know how can I improve this repo and what I've left out. 
It is very great that it's bi directional process. I will love to give you my feed back as well as my PRs.

**Comment by longnd** [comment]
So it is time to wrap up this stage of the code review process.
Thank you for your efforts so far. 
Our TA team will provide feedback to you by email shortly.
