### ISSUE TITLE
[Chore] UX Improvement - Handling issues when CSV format is not supported

### ISSUE THREAD

**Issue by longnd** [htoo-eain-lwin/seeker#22]
Issue
---
When uploading the CSV file in this format
```
keyword 1, keyword 2, keyword 3
```
The application treats it as a single keyword 
<img width="1044" alt="Screenshot 2023-01-09 at 12 17 33" src="https://user-images.githubusercontent.com/1896814/211244914-235247a7-eebd-4cf7-962f-bb1ebadfd59a.png">

it actually expects the following format
```
keyword 1
keyword 2
keyword 3
```
https://github.com/htoo-eain-lwin/seeker/blob/4315482b611377e5aaa853960ada2b02487b6de5/app/helpers/search_helper.rb#L3-L6
and it also does not validate if the CSV file exceeds the number of supported keywords
> This upload file can be in any size from 1 to 100 keywords.

When handling CSV uploads, the following best practices should be followed:
- Provide a template for users to download and fill
- Support both column and inline CSV formats
-  Show the list of properly parsed terms before doing the keyword processing, thus giving a chance to end-users to check what they uploaded before any kind of processing

**Comment by htoo-eain-lwin** [comment]
CSV service is now supporting both column and inline CSV formats.
Provided a template for users to download and refill.
